from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "metric_rca/runtime/ranking.py"


def replace_once(old: str, new: str) -> None:
    source = PATH.read_text(encoding="utf-8")
    count = source.count(old)
    if count != 1:
        raise RuntimeError(f"ranking.py: expected one replacement, found {count}")
    PATH.write_text(source.replace(old, new, 1), encoding="utf-8")


replace_once(
    "def _interaction_promoted_candidate(\n"
    "    *,\n"
    "    repository: Any,\n"
    "    run_id: str,\n"
    "    metric_id: str,\n"
    "    ranked_candidates: list[RootCauseCandidate],\n"
    ") -> RootCauseCandidate | None:\n"
    "    if metric_id not in {\"gmv\", \"uv\"}:\n"
    "        return None\n"
    "    if not _target_is_bad_direction_anomaly(repository=repository, run_id=run_id):\n"
    "        return None\n"
    "    for candidate in ranked_candidates:\n"
    "        if candidate.root_cause_type == RootCauseType.INTERACTION_CHANNEL_CATEGORY.value:\n"
    "            return candidate.model_copy(\n"
    "                update={\n"
    "                    \"evidence_ids\": _interaction_evidence_ids(\n"
    "                        repository=repository,\n"
    "                        run_id=run_id,\n"
    "                        pairs=_candidate_pairs(candidate),\n"
    "                        base_evidence_ids=candidate.evidence_ids,\n"
    "                    )\n"
    "                }\n"
    "            )\n"
    "        if candidate.dimension not in {\"channel\", \"category\"}:\n"
    "            continue\n"
    "        if _has_matching_signal_evidence(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            candidate=candidate,\n"
    "            required_bad_direction=True,\n"
    "        ):\n"
    "            continue\n"
    "        pairs = _candidate_pairs(candidate)\n"
    "        if not _has_dimension(pairs, \"channel\") or not _has_dimension(pairs, \"category\"):\n"
    "            continue\n"
    "        if _has_any_pair_matching_signal_evidence(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            pairs=pairs,\n"
    "            required_bad_direction=True,\n"
    "        ):\n"
    "            continue\n"
    "        evidence_ids = _interaction_evidence_ids(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            pairs=pairs,\n"
    "            base_evidence_ids=candidate.evidence_ids,\n"
    "        )\n"
    "        e_rank_id = f\"{run_id}:E_rank\"\n"
    "        if e_rank_id not in evidence_ids:\n"
    "            evidence_ids.append(e_rank_id)\n"
    "        return candidate.model_copy(\n"
    "            update={\n"
    "                \"root_cause_type\": RootCauseType.INTERACTION_CHANNEL_CATEGORY.value,\n"
    "                \"evidence_ids\": evidence_ids,\n"
    "            }\n"
    "        )\n"
    "    return None\n",
    "def _interaction_promoted_candidate(\n"
    "    *,\n"
    "    repository: Any,\n"
    "    run_id: str,\n"
    "    metric_id: str,\n"
    "    ranked_candidates: list[RootCauseCandidate],\n"
    ") -> RootCauseCandidate | None:\n"
    "    if metric_id not in {\"gmv\", \"uv\"}:\n"
    "        return None\n"
    "    if not _target_is_bad_direction_anomaly(repository=repository, run_id=run_id):\n"
    "        return None\n"
    "    for candidate in ranked_candidates:\n"
    "        pairs = _candidate_pairs(candidate)\n"
    "        if candidate.root_cause_type == RootCauseType.INTERACTION_CHANNEL_CATEGORY.value:\n"
    "            if not _has_verified_interaction_mechanism_evidence(\n"
    "                repository=repository,\n"
    "                run_id=run_id,\n"
    "                candidate=candidate,\n"
    "                required_bad_direction=True,\n"
    "            ):\n"
    "                continue\n"
    "            return candidate.model_copy(\n"
    "                update={\n"
    "                    \"evidence_ids\": _interaction_evidence_ids(\n"
    "                        repository=repository,\n"
    "                        run_id=run_id,\n"
    "                        pairs=pairs,\n"
    "                        base_evidence_ids=candidate.evidence_ids,\n"
    "                    )\n"
    "                }\n"
    "            )\n"
    "        if candidate.dimension not in {\"channel\", \"category\"}:\n"
    "            continue\n"
    "        if not _has_dimension(pairs, \"channel\") or not _has_dimension(pairs, \"category\"):\n"
    "            continue\n"
    "        if _has_matching_signal_evidence(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            candidate=candidate,\n"
    "            required_bad_direction=True,\n"
    "            excluded_signal_type=\"interaction\",\n"
    "        ):\n"
    "            continue\n"
    "        if _has_any_pair_matching_signal_evidence(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            pairs=pairs,\n"
    "            required_bad_direction=True,\n"
    "            excluded_signal_type=\"interaction\",\n"
    "        ):\n"
    "            continue\n"
    "        if not _has_verified_interaction_mechanism_evidence(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            candidate=candidate,\n"
    "            required_bad_direction=True,\n"
    "        ):\n"
    "            continue\n"
    "        evidence_ids = _interaction_evidence_ids(\n"
    "            repository=repository,\n"
    "            run_id=run_id,\n"
    "            pairs=pairs,\n"
    "            base_evidence_ids=candidate.evidence_ids,\n"
    "        )\n"
    "        e_rank_id = f\"{run_id}:E_rank\"\n"
    "        if e_rank_id not in evidence_ids:\n"
    "            evidence_ids.append(e_rank_id)\n"
    "        return candidate.model_copy(\n"
    "            update={\n"
    "                \"root_cause_type\": RootCauseType.INTERACTION_CHANNEL_CATEGORY.value,\n"
    "                \"evidence_ids\": evidence_ids,\n"
    "            }\n"
    "        )\n"
    "    return None\n",
)

replace_once(
    "def _has_any_pair_matching_signal_evidence(\n",
    "def _has_verified_interaction_mechanism_evidence(\n"
    "    *,\n"
    "    repository: Any,\n"
    "    run_id: str,\n"
    "    candidate: RootCauseCandidate,\n"
    "    required_bad_direction: bool,\n"
    ") -> bool:\n"
    "    pairs = _candidate_pairs(candidate)\n"
    "    if not _has_dimension(pairs, \"channel\") or not _has_dimension(pairs, \"category\"):\n"
    "        return False\n"
    "    for dimension in (\"channel\", \"category\"):\n"
    "        dimension_pairs = [\n"
    "            (pair_dimension, element)\n"
    "            for pair_dimension, element in pairs\n"
    "            if pair_dimension == dimension\n"
    "        ]\n"
    "        if not any(\n"
    "            _has_matching_signal_for_pair(\n"
    "                repository=repository,\n"
    "                run_id=run_id,\n"
    "                dimension=pair_dimension,\n"
    "                element=element,\n"
    "                required_bad_direction=required_bad_direction,\n"
    "                required_signal_type=\"interaction\",\n"
    "            )\n"
    "            for pair_dimension, element in dimension_pairs\n"
    "        ):\n"
    "            return False\n"
    "    return True\n\n\n"
    "def _signal_type_for_candidate(candidate: RootCauseCandidate) -> str | None:\n"
    "    by_root_cause = {\n"
    "        RootCauseType.CAMPAIGN_TRAFFIC_DROP.value: \"campaign\",\n"
    "        RootCauseType.CONVERSION_DROP.value: \"conversion\",\n"
    "        RootCauseType.STOCKOUT.value: \"inventory\",\n"
    "        RootCauseType.COMPLAINT_OR_QUALITY_ISSUE.value: \"refund_quality\",\n"
    "        RootCauseType.INTERACTION_CHANNEL_CATEGORY.value: \"interaction\",\n"
    "    }\n"
    "    return by_root_cause.get(candidate.root_cause_type)\n\n\n"
    "def _has_any_pair_matching_signal_evidence(\n",
)
